dev.dir = "C:/rtest/"
setNewversion(dev.dir = dev.dir,
              packs = c("startupmsg",
                        "SweaveListingUtils",
                        "distr",
                        "distrEx",
                        "distrDoc",
                        "distrSim",
                        "distrTEst",
                        "distrTeach",
                        "distrMod",
                        "RobAStBase",
                        "RandVar",
                        "ROptEst",
                        "RobLox",
                        "RobRex",
                        "ROptRegTS"),
              packs.dir = paste(dev.dir, c(rep("distr/pkg",9),
                               rep("RobASt/pkg",6)), sep=""),
              packs.ver = c("0.5.3", "0.1.1", 
                            "2.0.6", "2.0.3", "2.0.5",
                            "0.1.3","0.6.6","0.6.2",
                            "0.6.1", "0.6.1", "0.6.1"),
              packs.gtR = c("1.8.0", "2.0.0", "2.6.0", "2.6.0", "2.6.0",
                            "2.6.0", "2.6.0", "2.6.0", "2.6.0", "2.7.0",
                            "2.7.0", "2.7.0", "2.7.0", "2.4.0", "2.4.0"),
              withHTML = FALSE,
              packs.HTML.dir = c("", "", paste(dev.dir,
                     c(rep("distr/www",7)),sep=""),
                     rep("",6)),
              rkurs = FALSE,
              rkursDir = "D:/My Documents/altArbeit/R-Kurs/"
                           )
setNewversion(dev.dir = dev.dir,
              packs = c("startupmsg",
                        "SweaveListingUtils",
                        "distr",
                        "distrEx",
                        "distrDoc",
                        "distrSim",
                        "distrTEst",
                        "distrTeach",
                        "distrMod",
                        "RobAStBase",
                        "RandVar",
                        "ROptEst",
                        "RobLox",
                        "RobRex",
                        "ROptRegTS"),
              packs.dir = paste(dev.dir, c(rep("distr/branches/distr-2.1/pkg",9),
                               rep("RobASt/branches/robast-0.7/pkg",6)), sep=""),
              packs.ver = c("0.6", "0.2", rep("2.1",7),
                            "0.2",rep("0.7",5)),
              packs.gtR = c("1.8.0", "2.0.0", "2.2.0", "2.6.0", "2.6.0",
                            "2.6.0", "2.6.0", "2.2.0", "2.6.0", "2.7.0",
                            "2.7.0", "2.7.0", "2.7.0", "2.4.0", "2.4.0"),
              withHTML = FALSE,
              packs.HTML.dir = c("", "", paste(dev.dir,
                     c(rep("distr/www",7)),sep=""),
                     rep("",6)),
              rkurs = FALSE,
              rkursDir = "D:/My Documents/altArbeit/R-Kurs/"
                           )

