### from Matthias' thesis / ROptEst
setMethod("show", "ParamFamParameter", 
    function(object){
        cat(gettextf("An object of class \"%s\"\n", class(object)))
        cat(gettextf("name:\t%s\n", object@name))
        if(length(object@main) > 0){
            if(length(object@main) > 1){
                if(is.null(names(object@main)))
                    cat(paste(gettextf("element %s of main:\t%s\n", 1:length(object@main), object@main), collapse = ""))
                else{
                    cat(paste(gettextf("%s:\t%s\n", names(object@main), object@main), collapse = ""))
                }
            }else{
                if(is.null(names(object@main)))
                    cat(gettextf("main:\t%s\n", object@main))
                else{
                    cat(gettextf("%s:\t%s\n", names(object@main), object@main))
                }
            }
        }
        if(!is.null(object@nuisance) && length(object@nuisance)){
            if(length(object@main) > 1){
                if(is.null(names(object@nuisance)))
                    cat(paste(gettextf("element %s of nuisance:\t%s\n", 1:length(object@nuisance), object@nuisance), collapse = ""))
                else{
                    cat(gettext("nuisance:\n"))
                    cat(paste(gettextf("\t%s:\t%s\n", names(object@nuisance), object@nuisance), collapse = ""))
                }
            }else{
                if(is.null(names(object@nuisance)))
                    cat(gettextf("nuisance:\t%s\n", object@nuisance))
                else{
                    cat(gettext("nuisance:\n"))
                    cat(gettextf("\t%s:\t%s\n", names(object@nuisance), object@nuisance))
                }
            }
        }
        if(!identical(all.equal(object@trafo, diag(length(object)), 
                            tolerance = .Machine$double.eps^0.5), TRUE)){
            cat(gettext("trafo:\n"))
            print(object@trafo, quote = FALSE)
        }
    })
setMethod("show", "Symmetry", 
    function(object){ 
        cat(gettextf("type of symmetry:\t%s\n", object@type))
        if(!is.null(object@SymmCenter))
            cat(gettext("center of symmetry:\n"))
            print(object@SymmCenter, quote = FALSE)
    })
setMethod("show", "ParamFamily", 
    function(object){
        cat(gettextf("An object of class \"%s\"\n", class(object)))
        cat(gettextf("### name:\t%s\n", object@name))
        cat(gettext("\n### distribution:\t"))
        print(object@distribution, quote = FALSE)
        cat(gettext("\n### param:\t"))
        show(object@param)
        if(length(object@props) != 0){
            cat(gettext("\n### props:\n"))
            show(object@props)
        }
    })
setMethod("show", "RiskType", 
    function(object){
        cat(paste("An object of class", dQuote(class(object)), "\n"))
        cat("risk type:\t", object@type, "\n")
    })
setMethod("show", "asUnOvShoot", 
    function(object){
        cat(paste("An object of class", dQuote(class(object)), "\n"))
        cat("risk type:\t", object@type, "\n")
        cat("width:\t", object@width, "\n")
    })
setMethod("show", "asHampel", 
    function(object){
        cat(paste("An object of class", dQuote(class(object)), "\n"))
        cat("risk type:\t", object@type, "\n")
        cat("bound:\t", object@bound, "\n")
    })
setMethod("show", "fiUnOvShoot", 
    function(object){
        cat(paste("An object of class", dQuote(class(object)), "\n"))
        cat("risk type:\t", object@type, "\n")
        cat("width:\t", object@width, "\n")
    })
setMethod("show", "fiHampel", 
    function(object){
        cat(paste("An object of class", dQuote(class(object)), "\n"))
        cat("risk type:\t", object@type, "\n")
        cat("bound:\t", object@bound, "\n")
    })

setMethod("show", "Estimate", 
    function(object){
        digits <- getOption("digits")

        title <- gettextf("Evaluations of %s:\n", name(object))
        linet <- paste(paste(rep("-", nchar(title)-1),sep="",collapse=""),
                       "\n",sep="",collapse="") 
        cat(title)
        cat(linet)
        cat(gettextf("An object of class %s \n", dQuote(class(object))))
        cat(gettextf("generated by call\n  "))
        print(estimate.call(object), quote = FALSE)
        if(length(object@samplesize) > 0)
            cat(gettextf("samplesize:   %d\n",object@samplesize))
               
        
        trafo.mat <- object@trafo$mat
        trafo.fct <- object@trafo$fct

        l.x <- length(object@estimate)
        idx <- 1:l.x
           
        names.nuisance <- NULL
        if(!is.null(object@nuis.idx))
            {idx <- (-object@nuis.idx)
             names.nuisance <- names(object@estimate)[object@nuis.idx]
        }else{
        }

        
        
        estimate <- object@estimate[idx]
        
        if(!.isUnitMatrix(trafo.mat))
            estimate <- trafo.fct(estimate)$fval
        
        
        names.estimate <- names(estimate)
        
        if(!is.null(object@asvar)){
           traf0 <- diag(l.x)                

           if(!is.null(object@nuis.idx))
               traf0[idx,idx] <- trafo.mat
                         
           asvar <- traf0 %*% object@asvar %*% t(traf0)
           rownames(asvar) <- colnames(asvar) <- c(names.estimate, 
                                                   names.nuisance) 

           sd0 <- sqrt(diag(asvar)[idx]/object@samplesize)
           
           cat("estimate:\n")
       
        ### code borrowed from print.fitdistr in  package MASS by B.D. Ripley
           ans <- format(base::rbind(estimate, sd0), digits=digits)
           ans[1, ] <- sapply(ans[1, ], function(x) paste("", x))
           ans[2, ] <- sapply(ans[2, ], function(x) paste("(", x, ")", sep=""))
           ## only used for digits
           dn <- dimnames(ans)
           dn[[1]] <- rep("", 2)
           dn[[2]] <- paste(substring("      ", 1, 
                             (nchar(ans[2,]) - nchar(dn[[2]])) %/% 2), dn[[2]])
           dn[[2]] <- paste(dn[[2]], substring("      ", 1, 
                             (nchar(ans[2,]) - nchar(dn[[2]])) %/% 2))
           dimnames(ans) <- dn
           print(ans, quote = FALSE)
       ### end of borrowed code  

           cat("asymptotic (co)variance:\n")
           print(asvar, digits = digits, quote = FALSE)

        }else{

           cat("estimate:\n")
           print(estimate, digits = digits, quote = FALSE)

        } 
        if(!is.null(object@nuis.idx)){
           cat("nuisance parameter:\n")
           print(nuisance(object), digits = digits, quote = FALSE)        
           }
        if(!.isUnitMatrix(trafo.mat)){
           cat("Transformation of main parameter:\n")
           print(trafo.fct)   
           cat("Trafo / derivative matrix:\n")
           print(trafo.mat, digits = digits, quote = FALSE)                
           }
        
        if(nrow(object@Infos) > 0){
          cat("Infos:\n")
          print(object@Infos)
        }
    })

 setMethod("show", "MCEstimate", 
    function(object){
       digits <- getOption("digits")
       show(as(object,"Estimate"))
       cat("Criterium:\n")
       print(criterion(object), digits = digits, quote = FALSE)       
    })


setMethod("show", "Confint", 
    function(object){
        digits <- getOption("digits")
        cat(gettextf("A[n] %s confidence interval:\n",type(object)))
        print(confint(object), digits = digits, quote = FALSE)
        cat(gettextf("Type of estimator: %s:\n", name.estimate(object)))
        cat(gettextf("Call by which estimate was produced:\n"))
        print(estimate.call(object), quote = FALSE)

        if(!is.null(nuisance.estimate(object)))
           {cat(gettext("Nuisance parameter at which estimate was produced:\n"))
            print(nuisance.estimate(object), digits = digits, quote = FALSE)}

        trafo.mat <- object@trafo.estimate$mat
        trafo.fct <- object@trafo.estimate$fct
        
        if(!.isUnitMatrix(trafo.mat)){
           cat("Transformation of main parameter by which estimate was produced:\n")
           print(trafo.fct)   
           cat("Trafo / derivative matrix at which estimate was produced:\n")
           print(trafo.mat, digits = digits, quote = FALSE)                
           }
})


setMethod("print", "Estimate", 
    function(x, digits = getOption("digits")){
        oldDigits <- getOption("digits")
        options("digits" = digits)
        show(object = x)
        options("digits" = oldDigits)
        })

setMethod("print", "Confint", 
    function(x, digits = getOption("digits")){
        oldDigits <- getOption("digits")
        options("digits" = digits)
        show(object = x)
        options("digits" = oldDigits)
        })        